// Types for static image imports (e.g. `import icon from '@/donate_icon.png'`).
// next-env.d.ts declares these too, but it is generated by `next dev`/`next
// build` and git-ignored, so a fresh checkout (CI's type check runs before
// the build) would not have it.
/// <reference types="next/image-types/global" />
